security:
    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'
    providers:
        users_in_memory:
            memory:
                users:
                    admin:
                        password: '$argon2id$v=19$m=65536,t=4,p=1$LcOviLuEdBr7QJVjjolYvQ$DiFjFPVoQMGr5HsuWXfKfNAxHEd/z7ztbe4stGBZW7M'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern: ^/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
